# -*- coding: utf-8 -*-
"""Multilinear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRKnmV1lxvZCiO_cIbzMmIAglzjQgwU3

https://github.com/anitapathak/ML_lab_And_Assignment.git/
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

"""## ***Read the file***"""

df = pd.read_csv("/content/behavioral_indicators_internal_marks(1).csv")



"""***Data cleaning Process using mean replacment method ***



"""

# 1. Remove duplicates
df = df.drop_duplicates()

# 2. Convert numeric columns safely
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='ignore')

# 3. Fill missing values with column mean (only numeric)
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    df[col].fillna(df[col].mean(), inplace=True)

print("Data cleaned successfully")
print(df.isnull().sum())

df.info()

"""***finding corretion on different datasets and arranging the data***"""

target = "Total_Internal_Marks_50"

# Correlation with target
corr = df.corr(numeric_only=True)[target]

# Remove target itself and sort ascending
corr_sorted = corr.drop(target).sort_values(ascending=True)

print("Correlation with", target)
print(corr_sorted)

"""# Select features (X) and target (Y)"""

X = df[[
    "Lab_Attendance_Pct",
    "Theory_Attendance_Pct",
    "Assignment_PU_6_Set"

]]

Y = df["Total_Internal_Marks_50"]

"""***Plot the boxplot to see outliers ***"""

df[[
    "Lab_Attendance_Pct",
    "Theory_Attendance_Pct",
    "Assignment_PU_6_Set",
    "Total_Internal_Marks_50"
]].boxplot()
plt.xticks(rotation=45)
plt.title("Box Plot of All Features")
plt.show()

"""***Handling outliers***"""

cols = [
    "Lab_Attendance_Pct",
    "Theory_Attendance_Pct",
    "Assignment_PU_6_Set",
    "Total_Internal_Marks_50"
]

df_clean = df.copy()

for col in cols:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df_clean = df_clean[(df_clean[col] >= lower) & (df_clean[col] <= upper)]

"""***fit model to linear regression***"""

import pandas as pd
from sklearn.linear_model import LinearRegression


# Create model
model = LinearRegression()

# Fit model
model.fit(X, Y)

# Print coefficients
print("Intercept (a0):", model.intercept_)

print("\nCoefficients:")
for name, coef in zip(X.columns, model.coef_):
    print(name, ":", coef)


# Prediction
Y_pred = model.predict(X)

print("\nFirst 5 Predictions:")
print(Y_pred[:5])

"""***finding the equation of y=a0+a1x1+a2X2+a3X3***"""

a0 = model.intercept_

# Coefficients
coeffs = model.coef_

# Start equation string
equation = f"y = {a0:.4f}"

for name, coef in zip(X.columns, coeffs):
    equation += f" + ({coef:.4f})*{name}"

print("\nRegression Equation:")
print(equation)

"""***error finding using the absolute error and mean absolute error and R-squared  method***"""

# Predictions
Y_pred = model.predict(X)

# 1. Absolute Error (per sample)
absolute_error = abs(Y - Y_pred)

print("First 10 Absolute Errors:")
print(absolute_error[:10])

# 2. Mean Absolute Error (overall)
mae = mean_absolute_error(Y, Y_pred)
print("\nMean Absolute Error (MAE):", mae)

# 3. R-Square (R² Score)
r2 = r2_score(Y, Y_pred)
print("\nR-Square (R² Score):", r2)

"""***plot the linear graph ***"""

Y_pred = model.predict(X)

plt.figure()
plt.scatter(Y, Y_pred)
plt.xlabel("Actual Marks")
plt.ylabel("Predicted Marks")
plt.title("Actual vs Predicted Values")

# ideal line (perfect prediction)
plt.plot([Y.min(), Y.max()], [Y.min(), Y.max()])
plt.show()

"""*** Residual Plot (Error Distribution)***
  Random scatter around 0 → good model
  Pattern → model is biased or wrong ***bold text***
"""

residuals = Y - Y_pred

plt.figure()
plt.scatter(Y_pred, residuals)
plt.axhline(y=0, color='r')
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.show()

"""***Histogram of Errors***"""

plt.figure()
plt.hist(residuals, bins=10)
plt.xlabel("Error")
plt.ylabel("Frequency")
plt.title("Distribution of Prediction Errors")
plt.show()